### ISSUE TITLE
Will not compile on Linux with GLFW 3.1

### ISSUE THREAD

**Issue by ColinGilbert** [t-more/gambit-GLFW#1]
Hi,

I am currently trying to make this work on Gentoo with GLFW 3.1.Side note: Had to rename glfwContantconveter to glfwConstantConverter 
Unfortunately I am confronted with a wall of errors. :(

Edit: Took a chill pill; pardon my previous clippy tone. Edited out the snappy-sounding stuff and replaced it with generally nicer stuff. :)

```
noob@NoobKing ~/CoolCode/gambit-GLFW $ gsc -cc-options "-lglfw3" glfw.scm
*** INFO -- loading syntax expander
In file included from glfw.c:1008:0:
glfw.c: In function ‘long int ___H__20_glfw(___processor_state)’:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘uint8_t* {aka unsigned char*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:30429:20: note: in expansion of macro ‘___BODY’
 uint8_t* cvector = ___BODY(temp);
                    ^
glfw.c:30486:11: error: cannot convert ‘long int*’ to ‘unsigned char*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:30545:11: error: cannot convert ‘long int*’ to ‘unsigned char*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘uint16_t* {aka short unsigned int*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:30660:21: note: in expansion of macro ‘___BODY’
 uint16_t* cvector = ___BODY(temp);
                     ^
glfw.c:30717:11: error: cannot convert ‘long int*’ to ‘short unsigned int*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:30776:11: error: cannot convert ‘long int*’ to ‘short unsigned int*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘uint32_t* {aka unsigned int*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:30891:21: note: in expansion of macro ‘___BODY’
 uint32_t* cvector = ___BODY(temp);
                     ^
glfw.c:30948:11: error: cannot convert ‘long int*’ to ‘unsigned int*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:31007:11: error: cannot convert ‘long int*’ to ‘unsigned int*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:35: error: invalid conversion from ‘long int*’ to ‘uint64_t* {aka long unsigned int*}’ [-fpermissive]
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                   ^
glfw.c:31122:21: note: in expansion of macro ‘___BODY’
 uint64_t* cvector = ___BODY(temp);
                     ^
/usr/local/Gambit-C/include/gambit.h:2200:35: error: invalid conversion from ‘long int*’ to ‘long unsigned int*’ [-fpermissive]
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                   ^
glfw.c:31179:13: note: in expansion of macro ‘___BODY’
 ___result = ___BODY(___arg1);
             ^
glfw.c:31238:30: error: invalid conversion from ‘long int*’ to ‘long unsigned int*’ [-fpermissive]
 ___result = ___BODY(___arg1) + ___arg2;
                              ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘int8_t* {aka signed char*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:31352:19: note: in expansion of macro ‘___BODY’
 int8_t* cvector = ___BODY(temp);
                   ^
glfw.c:31409:11: error: cannot convert ‘long int*’ to ‘signed char*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:31468:11: error: cannot convert ‘long int*’ to ‘signed char*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘int16_t* {aka short int*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:31583:20: note: in expansion of macro ‘___BODY’
 int16_t* cvector = ___BODY(temp);
                    ^
glfw.c:31640:11: error: cannot convert ‘long int*’ to ‘short int*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:31699:11: error: cannot convert ‘long int*’ to ‘short int*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘int32_t* {aka int*}’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:31814:20: note: in expansion of macro ‘___BODY’
 int32_t* cvector = ___BODY(temp);
                    ^
glfw.c:31871:11: error: cannot convert ‘long int*’ to ‘int*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:31930:11: error: cannot convert ‘long int*’ to ‘int*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘float*’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:32276:18: note: in expansion of macro ‘___BODY’
 float* cvector = ___BODY(temp);
                  ^
glfw.c:32333:11: error: cannot convert ‘long int*’ to ‘float*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:32392:11: error: cannot convert ‘long int*’ to ‘float*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
In file included from glfw.c:1008:0:
/usr/local/Gambit-C/include/gambit.h:2200:47: error: cannot convert ‘long int*’ to ‘double*’ in initialization
 #define ___BODY(obj)(___UNTAG(obj)+___BODY_OFS)
                                               ^
glfw.c:32507:19: note: in expansion of macro ‘___BODY’
 double* cvector = ___BODY(temp);
                   ^
glfw.c:32564:11: error: cannot convert ‘long int*’ to ‘double*’ in assignment
 ___result = ___BODY(___arg1);
           ^
glfw.c:32623:11: error: cannot convert ‘long int*’ to ‘double*’ in assignment
 ___result = ___BODY(___arg1) + ___arg2;
           ^
glfw.c:32681:28: error: ‘malloc’ was not declared in this scope
 int* n = malloc(sizeof(int)); *n = ___arg1; ___result = n;
                            ^
glfw.c:32851:13: error: ‘free’ was not declared in this scope
 free(___arg1);
             ^
glfw.c:42067:38: error: cannot convert ‘short unsigned int*’ to ‘unsigned int*’ in assignment
 GLFWgammaramp x = *___arg1;___result = x.red;
                                      ^
glfw.c:42124:38: error: cannot convert ‘short unsigned int*’ to ‘unsigned int*’ in assignment
 GLFWgammaramp x = *___arg1;___result = x.green;
                                      ^
glfw.c:42181:38: error: cannot convert ‘short unsigned int*’ to ‘unsigned int*’ in assignment
 GLFWgammaramp x = *___arg1;___result = x.blue;
                                      ^
In file included from glfw.c:1008:0:
glfw.c:42448:45: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 ___CFUN_CALL(___result,glfwGetVersionString())
                                             ^
/usr/local/Gambit-C/include/gambit.h:6726:33: note: in definition of macro ‘___CFUN_CALL’
 #define ___CFUN_CALL(r,call)r = call;
                                 ^
glfw.c:42500:70: error: invalid conversion from ‘void (*)(int, char*)’ to ‘GLFWerrorfun {aka void (*)(int, const char*)}’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetErrorCallback(___arg1))
                                                                      ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
In file included from glfw.c:5025:0:
/usr/include/GLFW/glfw3.h:1245:22: error:   initializing argument 1 of ‘void (* glfwSetErrorCallback(GLFWerrorfun))(int, const char*)’ [-fpermissive]
 GLFWAPI GLFWerrorfun glfwSetErrorCallback(GLFWerrorfun cbfun);
                      ^
In file included from glfw.c:1008:0:
glfw.c:42500:70: error: invalid conversion from ‘GLFWerrorfun {aka void (*)(int, const char*)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetErrorCallback(___arg1))
                                                                      ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43451:84: error: invalid conversion from ‘GLFWwindowclosefun {aka void (*)(GLFWwindow*)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowCloseCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43517:84: error: invalid conversion from ‘void (*)(GLFWwindow*, bool)’ to ‘GLFWwindowfocusfun {aka void (*)(GLFWwindow*, int)}’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowFocusCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
In file included from glfw.c:5025:0:
/usr/include/GLFW/glfw3.h:2252:28: error:   initializing argument 2 of ‘void (* glfwSetWindowFocusCallback(GLFWwindow*, GLFWwindowfocusfun))(GLFWwindow*, int)’ [-fpermissive]
 GLFWAPI GLFWwindowfocusfun glfwSetWindowFocusCallback(GLFWwindow* window, GLFWwindowfocusfun cbfun);
                            ^
In file included from glfw.c:1008:0:
glfw.c:43517:84: error: invalid conversion from ‘GLFWwindowfocusfun {aka void (*)(GLFWwindow*, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowFocusCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43583:86: error: invalid conversion from ‘void (*)(GLFWwindow*, bool)’ to ‘GLFWwindowiconifyfun {aka void (*)(GLFWwindow*, int)}’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowIconifyCallback(___arg1,___arg2))
                                                                                      ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
In file included from glfw.c:5025:0:
/usr/include/GLFW/glfw3.h:2274:30: error:   initializing argument 2 of ‘void (* glfwSetWindowIconifyCallback(GLFWwindow*, GLFWwindowiconifyfun))(GLFWwindow*, int)’ [-fpermissive]
 GLFWAPI GLFWwindowiconifyfun glfwSetWindowIconifyCallback(GLFWwindow* window, GLFWwindowiconifyfun cbfun);
                              ^
In file included from glfw.c:1008:0:
glfw.c:43583:86: error: invalid conversion from ‘GLFWwindowiconifyfun {aka void (*)(GLFWwindow*, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowIconifyCallback(___arg1,___arg2))
                                                                                      ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43649:82: error: invalid conversion from ‘GLFWwindowposfun {aka void (*)(GLFWwindow*, int, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowPosCallback(___arg1,___arg2))
                                                                                  ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43715:86: error: invalid conversion from ‘GLFWwindowrefreshfun {aka void (*)(GLFWwindow*)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowRefreshCallback(___arg1,___arg2))
                                                                                      ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43781:83: error: invalid conversion from ‘GLFWwindowsizefun {aka void (*)(GLFWwindow*, int, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetWindowSizeCallback(___arg1,___arg2))
                                                                                   ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:43841:54: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 ___CFUN_CALL(___result,glfwGetClipboardString(___arg1))
                                                      ^
/usr/local/Gambit-C/include/gambit.h:6726:33: note: in definition of macro ‘___CFUN_CALL’
 #define ___CFUN_CALL(r,call)r = call;
                                 ^
glfw.c:44203:50: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 ___CFUN_CALL(___result,glfwGetMonitorName(___arg1))
                                                  ^
/usr/local/Gambit-C/include/gambit.h:6726:33: note: in definition of macro ‘___CFUN_CALL’
 #define ___CFUN_CALL(r,call)r = call;
                                 ^
glfw.c:44259:72: error: invalid conversion from ‘GLFWmonitorfun {aka void (*)(GLFWmonitor*, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetMonitorCallback(___arg1))
                                                                        ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:44321:74: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_POINTER(___result_voidstar,glfwGetVideoModes(___arg1,___arg2))
                                                                          ^
/usr/local/Gambit-C/include/gambit.h:6730:41: note: in definition of macro ‘___CFUN_CALL_POINTER’
 #define ___CFUN_CALL_POINTER(r,call)r = call;
                                         ^
glfw.c:44382:65: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_POINTER(___result_voidstar,glfwGetVideoMode(___arg1))
                                                                 ^
/usr/local/Gambit-C/include/gambit.h:6730:41: note: in definition of macro ‘___CFUN_CALL_POINTER’
 #define ___CFUN_CALL_POINTER(r,call)r = call;
                                         ^
glfw.c:44499:65: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_POINTER(___result_voidstar,glfwGetGammaRamp(___arg1))
                                                                 ^
/usr/local/Gambit-C/include/gambit.h:6730:41: note: in definition of macro ‘___CFUN_CALL_POINTER’
 #define ___CFUN_CALL_POINTER(r,call)r = call;
                                         ^
glfw.c:44694:88: error: invalid conversion from ‘GLFWframebuffersizefun {aka void (*)(GLFWwindow*, int, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetFramebufferSizeCallback(___arg1,___arg2))
                                                                                        ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:44855:68: error: invalid conversion from ‘GLFWglproc {aka void (*)()}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwGetProcAddress(___arg1))
                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45352:76: error: invalid conversion from ‘GLFWkeyfun {aka void (*)(GLFWwindow*, int, int, int, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetKeyCallback(___arg1,___arg2))
                                                                            ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45418:77: error: invalid conversion from ‘GLFWcharfun {aka void (*)(GLFWwindow*, unsigned int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetCharCallback(___arg1,___arg2))
                                                                             ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45684:84: error: invalid conversion from ‘GLFWmousebuttonfun {aka void (*)(GLFWwindow*, int, int, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetMouseButtonCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45750:82: error: invalid conversion from ‘GLFWcursorposfun {aka void (*)(GLFWwindow*, double, double)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetCursorPosCallback(___arg1,___arg2))
                                                                                  ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45816:84: error: invalid conversion from ‘void (*)(GLFWwindow*, bool)’ to ‘GLFWcursorenterfun {aka void (*)(GLFWwindow*, int)}’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetCursorEnterCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
In file included from glfw.c:5025:0:
/usr/include/GLFW/glfw3.h:2908:28: error:   initializing argument 2 of ‘void (* glfwSetCursorEnterCallback(GLFWwindow*, GLFWcursorenterfun))(GLFWwindow*, int)’ [-fpermissive]
 GLFWAPI GLFWcursorenterfun glfwSetCursorEnterCallback(GLFWwindow* window, GLFWcursorenterfun cbfun);
                            ^
In file included from glfw.c:1008:0:
glfw.c:45816:84: error: invalid conversion from ‘GLFWcursorenterfun {aka void (*)(GLFWwindow*, int)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetCursorEnterCallback(___arg1,___arg2))
                                                                                    ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:45882:79: error: invalid conversion from ‘GLFWscrollfun {aka void (*)(GLFWwindow*, double, double)}’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_FUNCTION(___result_voidstar,glfwSetScrollCallback(___arg1,___arg2))
                                                                               ^
/usr/local/Gambit-C/include/gambit.h:6732:42: note: in definition of macro ‘___CFUN_CALL_FUNCTION’
 #define ___CFUN_CALL_FUNCTION(r,call)r = call;
                                          ^
glfw.c:46000:76: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_POINTER(___result_voidstar,glfwGetJoystickAxes(___arg1,___arg2))
                                                                            ^
/usr/local/Gambit-C/include/gambit.h:6730:41: note: in definition of macro ‘___CFUN_CALL_POINTER’
 #define ___CFUN_CALL_POINTER(r,call)r = call;
                                         ^
glfw.c:46064:79: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
 ___CFUN_CALL_POINTER(___result_voidstar,glfwGetJoystickButtons(___arg1,___arg2))
                                                                               ^
/usr/local/Gambit-C/include/gambit.h:6730:41: note: in definition of macro ‘___CFUN_CALL_POINTER’
 #define ___CFUN_CALL_POINTER(r,call)r = call;
                                         ^
glfw.c:46123:51: error: invalid conversion from ‘void (*)(GLFWwindow*, int, int, int, int)’ to ‘int’ [-fpermissive]
 ___CFUN_CALL(___result,glfwGetJoystickName(___arg1))
                                                   ^
/usr/local/Gambit-C/include/gambit.h:6726:33: note: in definition of macro ‘___CFUN_CALL’
 #define ___CFUN_CALL(r,call)r = call;
                                 ^
In file included from glfw.c:5025:0:
/usr/include/GLFW/glfw3.h:3060:21: error:   initializing argument 1 of ‘const char* glfwGetJoystickName(int)’ [-fpermissive]
 GLFWAPI const char* glfwGetJoystickName(int joy);
                     ^
In file included from glfw.c:1008:0:
glfw.c:46123:51: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
 ___CFUN_CALL(___result,glfwGetJoystickName(___arg1))
                                                   ^
/usr/local/Gambit-C/include/gambit.h:6726:33: note: in definition of macro ‘___CFUN_CALL’
 #define ___CFUN_CALL(r,call)r = call;
                                 ^
glfw.c:46275:11: error: invalid conversion from ‘GLFWwindow*’ to ‘int’ [-fpermissive]
 ___result = ___arg1;
           ^
*** ERROR IN ##main -- C compilation or link failed while compiling "glfw.scm"

```

Would it be required to change a few API definitions, or is this a more fundamental problem? I am rather new to Scheme and would much prefer to use Gambit.

Thanks!
Colin

**Comment by t-more** [comment]
Hey!
I know this is a bit late (very, very, very late). 
Is this still interesting for you?
If so what version of Gambit where you using?

Best, Tomas
